# Generated by Django 4.1 on 2023-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('itemType', models.CharField(max_length=200)),
                ('assetType', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('devproductId', models.IntegerField()),
                ('genres', models.CharField(max_length=200)),
                ('itemStatus', models.CharField(max_length=200)),
                ('itemRestrictions', models.CharField(max_length=200)),
                ('creatorHasVerifiedBadge', models.CharField(max_length=200)),
                ('creatorType', models.CharField(max_length=200)),
                ('creatorTargetId', models.IntegerField()),
                ('creatorName', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('favoriteCount', models.IntegerField()),
                ('offSaleDeadline', models.CharField(max_length=200)),
                ('saleLocationType', models.CharField(max_length=200)),
            ],
        ),
    ]
